runtime: nodejs18
service: northstar-report-web
instance_class: F2

handlers:
  - url: /(.+\.(js|css|png|jpg|gif|svg|ico|json|html|map))$
    static_files: build/\1
    upload: build/(.+\.(js|css|png|jpg|gif|svg|ico|json|html|map))$

  - url: /(.+)
    static_files: build/index.html
    upload: build/index.html

  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production
